In [3]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.autograd
from torchvision import datasets, transforms
import termcolor
import torch.utils.data as data
import torch.optim as optim
import random

## Create Training Data

In [39]:
xs = torch.rand(1000)
ys = 2 * xs

## Instantiate Network

In [35]:
class MyNetwork(nn.Module):
    
    def __init__(self):
        """Define the network architecture."""
        super(MyNetwork, self).__init__()
        self.fc = nn.Linear(1, 1, False)

    def forward(self, data):
        """Defines what inference means."""
        return self.fc(data)

In [36]:
N = MyNetwork()
print(N)

MyNetwork(
  (fc): Linear(in_features=1, out_features=1, bias=False)
)


In [48]:
for index, param in enumerate(N.parameters()):
    param_type = "Weights" if index % 2 == 0 else "Bias"
    print(termcolor.colored(f"Layer {index} {param_type}", attrs=["reverse"]))
    print(param)

Layer 0 Weights
Parameter containing:
tensor([[2.0000]], requires_grad=True)


In [49]:
# iterate through the layers of the network
for index, child in enumerate(N.children()):
    print(termcolor.colored(f"Layer {index}", attrs=["reverse"]))
    print(child)
    print(child.weight)
    print(child.bias)

Layer 0
Linear(in_features=1, out_features=1, bias=False)
Parameter containing:
tensor([[2.0000]], requires_grad=True)
None


In [50]:
optimizer = optim.SGD(N.parameters(), lr=0.1)
for x, y in zip(xs, ys):
    y_hat = N(x.reshape(1))
#     print(f"x: {x}, y: {y}, y_hat: {y_hat}")
    loss = (y - y_hat) ** 2
    loss.backward()
    optimizer.step()
    optimizer.zero_grad()

In [51]:
x = torch.tensor([1., 2., 3.], requires_grad=True)

In [54]:
x[2].backward()

In [55]:
x.grad

tensor([0., 0., 1.])